### ISSUE TITLE
How to initiate teledraw canvas in Meteor?

### ISSUE THREAD

**Issue by ducdev** [lakenen/teledraw-canvas#7]
Hello,

It seems I can not put this inside Template onRendered in Meteor.

```
const canvas = new TeledrawCanvas('test-canvas');
```

But it works if I paste into browser console and enter.

**Comment by lakenen** [comment]
I'm not too familiar with Meteor. Are there any error messages? Perhaps the element doesn't exist yet when this script runs?

**Comment by ducdev** [comment]
@lakenen I used jQuery for initiating and event handlers and it works flawlessly, `onRendered()` in Meteor Blaze may not good in this case. Thanks for crafting this.
