### ISSUE TITLE
How to make size of drawing canvas like percentage of screen size, not fixed pixel size?

### ISSUE THREAD

**Issue by ducdev** [lakenen/teledraw-canvas#8]
Hi @lakenen How to make size of drawing canvas like percentage of screen size, not fixed pixel size? I need to make it fit all screen from 1280x800 to full HD or 4K.

**Comment by lakenen** [comment]
@ducdev do you want the size to change if the browser is resized, or just set the size once?

If you are okay with setting the size only once, you could initialize the canvas with the appropriate size like this:

```js
// you can change the size depending on your needs, for example 50%:
var width = window.innerWidth * 0.5;
var height = window.innerHeight * 0.5;
var canvas = new TeledrawCanvas('test-canvas', {
    width: width, 
    height: height
});
```
